#!/usr/bin/env python3
"""
Patch service type files to add ROS 2-style wrapper classes.

This script automatically adds ROS 2-compatible wrapper classes to SWIG-generated
service type files. For each service (e.g., SetBool, Trigger), it creates a wrapper
class that combines Request and Response classes.

The script handles two patterns:
1. Split files: ServiceName_Request.py and ServiceName_Response.py
2. Single file: ServiceName.py containing both ServiceName_Request and ServiceName_Response

The script is designed to be:
- Idempotent: Can be run multiple times safely
- Generic: Works with any ROS 2 service definition
- Automatic: Detects service components and generates appropriate wrappers

Usage:
    python patch_service_types.py <install_root>

Example:
    python patch_service_types.py /opt/fast-dds-v3-libs/python/src
"""
import os
import sys
import re
from pathlib import Path
from typing import List, Tuple, Set

def find_service_pairs(srv_dir: Path) -> Set[str]:
    """
    Find service Request/Response pairs in a srv directory.
    Returns a set of service base names (e.g., {'SetBool', 'Trigger'}).
    """
    files = [f.name for f in srv_dir.glob('*.py')]
    
    services = set()
    for filename in files:
        if filename.endswith('_Request.py'):
            service_name = filename.replace('_Request.py', '')
            response_file = f'{service_name}_Response.py'
            if response_file in files:
                services.add(service_name)
    
    return services


def find_single_file_services(srv_dir: Path) -> List[Tuple[str, str]]:
    """
    Find services where Request and Response are defined in a single file.
    E.g., CancelGoal.py containing CancelGoal_Request and CancelGoal_Response classes.
    Returns a list of tuples: (service_name, filename).
    """
    services = []
    
    for py_file in srv_dir.glob('*.py'):
        # Skip wrapper files, library files, and package init
        if py_file.name.startswith('_') or \
           py_file.name.startswith('lib') or \
           py_file.name == '__init__.py':
            continue
        
        # Skip if it's a _Request.py or _Response.py file
        if py_file.name.endswith('_Request.py') or py_file.name.endswith('_Response.py'):
            continue
        
        service_name = py_file.stem
        content = py_file.read_text()
        
        # Check if file contains both Request and Response classes
        has_request = f'class {service_name}_Request' in content
        has_response = f'class {service_name}_Response' in content
        already_patched = f'class {service_name}:' in content or f'class {service_name}(' in content
        
        if has_request and has_response and not already_patched:
            services.append((service_name, py_file.name))
    
    return services


def patch_single_file_service(srv_dir: Path, service_name: str, filename: str, verbose: bool = True) -> bool:
    """
    Add a wrapper class to a single-file service (like CancelGoal.py).
    
    Args:
        srv_dir: Path to the srv directory
        service_name: Name of the service (e.g., 'CancelGoal')
        filename: Name of the Python file
        verbose: Whether to print progress messages
    
    Returns:
        True if patched, False if skipped
    """
    filepath = srv_dir / filename
    
    wrapper_code = f'''

# ROS 2-style service wrapper (auto-generated by patch_service_types.py)
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {service_name}_Request
    Response = {service_name}_Response
'''
    
    content = filepath.read_text()
    filepath.write_text(content + wrapper_code)
    
    if verbose:
        print(f"  [PATCH] {filepath.relative_to(filepath.parents[2])}: added {service_name} wrapper")
    
    return True


def patch_service_init(srv_dir: Path, verbose: bool = True) -> int:
    """
    Add ROS 2-style wrapper classes to __init__.py for all service pairs.
    
    Args:
        srv_dir: Path to the srv directory
        verbose: Whether to print progress messages
    
    Returns:
        Number of services patched
    """
    init_file = srv_dir / '__init__.py'
    
    if not init_file.exists():
        if verbose:
            print(f"  [SKIP] __init__.py: file not found")
        return 0
    
    content = init_file.read_text()
    services = find_service_pairs(srv_dir)
    
    if not services:
        if verbose:
            print(f"  [SKIP] No service pairs found")
        return 0
    
    patched_count = 0
    additions = []
    
    for service_name in sorted(services):
        request_class = f'{service_name}_Request'
        response_class = f'{service_name}_Response'
        
        # Check if wrapper class already exists
        if f'class {service_name}:' in content or f'class {service_name}(' in content:
            if verbose:
                print(f"  [SKIP] {service_name}: wrapper already exists")
            continue
        
        # Check if Request/Response are imported
        if f'import {request_class}' not in content and f'from .{request_class}' not in content:
            if verbose:
                print(f"  [SKIP] {service_name}: {request_class} not imported")
            continue
        
        # Create wrapper class
        wrapper_code = f'''

# ROS 2-style service wrapper for {service_name}
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {request_class}
    Response = {response_class}
'''
        additions.append(wrapper_code)
        if verbose:
            print(f"  [PATCH] {service_name}: added wrapper")
        patched_count += 1
    
    if additions:
        # Append all wrapper classes to __init__.py
        init_file.write_text(content + '\n# ROS 2-style service wrappers (auto-generated by patch_service_types.py)\n' + ''.join(additions))
    
    return patched_count


def find_srv_directories(root_dir: Path) -> List[Path]:
    """Find all srv/ directories in the install root."""
    return sorted([d for d in root_dir.rglob('srv') if d.is_dir()])


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    root_dir = Path(sys.argv[1])
    
    if not root_dir.exists() or not root_dir.is_dir():
        print(f"[ERROR] Install root does not exist or is not a directory: {root_dir}")
        sys.exit(1)
    
    print(f"[INFO] Scanning for srv directories in {root_dir}")
    srv_dirs = find_srv_directories(root_dir)
    
    if not srv_dirs:
        print("[INFO] No srv directories found")
        return 0
    
    print(f"[INFO] Found {len(srv_dirs)} srv directories")
    
    total_patched = 0
    
    for srv_dir in srv_dirs:
        print(f"\n[INFO] Processing {srv_dir.relative_to(root_dir)}")
        
        # Patch split-file services (via __init__.py)
        patched_count = patch_service_init(srv_dir, verbose=True)
        total_patched += patched_count
        
        # Patch single-file services
        single_file_services = find_single_file_services(srv_dir)
        for service_name, filename in single_file_services:
            if patch_single_file_service(srv_dir, service_name, filename, verbose=True):
                total_patched += 1
    
    print(f"\n[INFO] Patched {total_patched} service wrappers across {len(srv_dirs)} packages")
    
    if total_patched > 0:
        print("[INFO] ROS 2-style service wrappers applied successfully")
    
    return 0

if __name__ == '__main__':
    sys.exit(main())
