#!/usr/bin/env python3
"""
Patch action type files to add ROS 2-style wrapper classes.

This script automatically adds ROS 2-compatible wrapper classes to SWIG-generated
action type files. For each action (e.g., Fibonacci), it creates a wrapper class
that provides:
- Goal, Result, Feedback message proxies
- SendGoal, GetResult service interfaces
- FeedbackMessage type
- CancelGoal service reference (from action_msgs)

The script is designed to be:
- Idempotent: Can be run multiple times safely
- Generic: Works with any ROS 2 action definition
- Automatic: Detects action components and generates appropriate wrappers

Usage:
    python patch_action_types.py <install_root>

Example:
    python patch_action_types.py /opt/fast-dds-v3-libs/python/src
"""
import os
import sys
import re
from pathlib import Path
from typing import List, Dict, Tuple, Optional

def validate_action_components(content: str, action_name: str) -> Tuple[bool, List[str]]:
    """
    Validate that all required action components exist in the file.
    Returns (is_valid, missing_components).
    """
    required_components = [
        f'{action_name}_Goal',
        f'{action_name}_Result',
        f'{action_name}_Feedback',
        f'{action_name}_SendGoal_Request',
        f'{action_name}_SendGoal_Response',
        f'{action_name}_GetResult_Request',
        f'{action_name}_GetResult_Response',
        f'{action_name}_FeedbackMessage',
    ]
    
    missing = []
    for component in required_components:
        if f'class {component}' not in content:
            missing.append(component)
    
    return len(missing) == 0, missing


def extract_package_name(action_file: str) -> str:
    """Extract package name from action file path."""
    parts = action_file.split(os.sep)
    try:
        action_idx = parts.index('action')
        return parts[action_idx - 1] if action_idx > 0 else 'unknown'
    except (ValueError, IndexError):
        return 'unknown'


def patch_action_file(action_file: str, verbose: bool = True) -> bool:
    """
    Add ROS 2-style wrapper class to an action file.
    
    Args:
        action_file: Path to the action Python file
        verbose: Whether to print detailed progress messages
    
    Returns:
        True if file was patched, False if skipped
    """
    action_path = Path(action_file)
    
    if not action_path.exists():
        if verbose:
            print(f"[ERROR] {action_file}: file does not exist")
        return False
    
    content = action_path.read_text()
    action_name = action_path.stem
    
    # Check if wrapper class already exists
    if f'class {action_name}:' in content or f'class {action_name}(' in content:
        if verbose:
            print(f"  [SKIP] {action_path.relative_to(action_path.parents[2])}: wrapper already exists")
        return False
    
    # Validate action components
    is_valid, missing = validate_action_components(content, action_name)
    if not is_valid:
        if verbose:
            print(f"  [SKIP] {action_path.relative_to(action_path.parents[2])}: missing components: {', '.join(missing[:3])}")
        return False
    
    # Detect package name
    package_name = extract_package_name(action_file)
    
    # Create wrapper class with property-based proxy for Goal/Result/Feedback
    wrapper_code = f'''

# ROS 2-style action wrapper (auto-generated by patch_action_types.py)
# Note: All ROS 2 actions depend on action_msgs.srv.CancelGoal per ROS 2 specification

class _MessageProxy:
    """Proxy that converts attribute access to SWIG method calls for ROS 2 compatibility."""
    def __init__(self, swig_cls):
        object.__setattr__(self, '_swig_cls', swig_cls)
    
    def __call__(self, *args, **kwargs):
        instance = self._swig_cls(*args, **kwargs)
        return _MessageProxyInstance(instance)

class _MessageProxyInstance:
    """Instance proxy that wraps SWIG message instances for ROS 2-style attribute access."""
    def __init__(self, swig_instance):
        object.__setattr__(self, '_instance', swig_instance)

    def __getattribute__(self, name):
        if name == '_instance':
            return object.__getattribute__(self, '_instance')
        instance = object.__getattribute__(self, '_instance')
        # Try name first, then name_ (SWIG trailing underscore convention)
        try:
            attr = getattr(instance, name)
        except AttributeError:
            # SWIG may add trailing underscore for C++ member variables
            attr = getattr(instance, name + '_')
        # If it's a zero-arg callable (SWIG getter), call it
        if callable(attr):
            try:
                val = attr()
                # Convert SWIG vectors to Python lists for usability
                if (hasattr(val, '__iter__') and hasattr(val, 'size')
                        and not isinstance(val, (str, bytes))):
                    try:
                        return list(val)
                    except Exception:
                        pass
                return val
            except TypeError:
                return attr
        return attr

    def __setattr__(self, name, value):
        instance = object.__getattribute__(self, '_instance')
        # Try name first, then name_ (SWIG trailing underscore convention)
        attr = None
        actual_name = name
        try:
            attr = getattr(instance, name, None)
        except Exception:
            pass
        if attr is None:
            try:
                attr = getattr(instance, name + '_', None)
                if attr is not None:
                    actual_name = name + '_'
            except Exception:
                pass
        # If attribute is a method, try calling it with the value (SWIG setter pattern)
        if callable(attr):
            try:
                attr(value)
                return
            except (TypeError, AttributeError):
                pass
            # For Python list -> SWIG vector: get the vector, clear, push_back
            if isinstance(value, (list, tuple)):
                try:
                    vec = attr()  # Call getter to get the SWIG vector
                    if hasattr(vec, 'clear') and hasattr(vec, 'push_back'):
                        vec.clear()
                        for item in value:
                            vec.push_back(item)
                        return
                except Exception:
                    pass
        # Fall back to direct attribute assignment
        try:
            setattr(instance, actual_name, value)
        except AttributeError:
            object.__setattr__(instance, actual_name, value)

    def __getattr__(self, name):
        instance = object.__getattribute__(self, '_instance')
        return getattr(instance, name)

    # Return the wrapped SWIG instance to support passing to C++ code
    def __repr__(self):
        return repr(object.__getattribute__(self, '_instance'))

    def __str__(self):
        return str(object.__getattribute__(self, '_instance'))

class {action_name}:
    """ROS 2-style action type for {action_name} (package: {package_name})."""
    Goal = _MessageProxy({action_name}_Goal)
    Result = _MessageProxy({action_name}_Result)
    Feedback = _MessageProxy({action_name}_Feedback)
    
    # SendGoal service
    class SendGoal:
        Request = {action_name}_SendGoal_Request
        Response = {action_name}_SendGoal_Response
    
    # GetResult service
    class GetResult:
        Request = {action_name}_GetResult_Request
        Response = {action_name}_GetResult_Response
    
    FeedbackMessage = {action_name}_FeedbackMessage
    
    # CancelGoal service (standardized across all ROS 2 actions via action_msgs)
    # Import with fallback to handle missing dependencies gracefully
    try:
        from action_msgs.srv import CancelGoal as _CancelGoal
        CancelGoal = _CancelGoal
    except ImportError:
        # If action_msgs is not available, CancelGoal will be None
        # This allows the action type to load, but cancel functionality will be unavailable
        CancelGoal = None
'''
    
    # Append wrapper code to file
    action_path.write_text(content + wrapper_code)
    
    if verbose:
        print(f"  [PATCH] {action_path.relative_to(action_path.parents[2])}: added {action_name} wrapper")
    
    return True


def find_action_files(root_dir: Path) -> List[Path]:
    """Find all action Python files in the install root."""
    action_files = []
    
    # Find all action/ directories
    for action_dir in root_dir.rglob('action'):
        if not action_dir.is_dir():
            continue
        
        # Find action .py files (exclude internal/wrapper files)
        for py_file in action_dir.glob('*.py'):
            # Skip wrapper files, library files, and package init
            if py_file.name.startswith('_') or \
               py_file.name.startswith('lib') or \
               py_file.name == '__init__.py':
                continue
            
            # Must contain action component classes
            content = py_file.read_text()
            action_name = py_file.stem
            if f'class {action_name}_Goal' in content:
                action_files.append(py_file)
    
    return sorted(action_files)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    root_dir = Path(sys.argv[1])
    
    if not root_dir.exists() or not root_dir.is_dir():
        print(f"[ERROR] Install root does not exist or is not a directory: {root_dir}")
        sys.exit(1)
    
    print(f"[INFO] Scanning for action files in {root_dir}")
    action_files = find_action_files(root_dir)
    
    if not action_files:
        print("[INFO] No action files found")
        return 0
    
    print(f"[INFO] Found {len(action_files)} action files")
    
    patched_count = 0
    skipped_count = 0
    
    for action_file in action_files:
        if patch_action_file(str(action_file), verbose=True):
            patched_count += 1
        else:
            skipped_count += 1
    
    print(f"\n[INFO] Patched {patched_count}/{len(action_files)} action files")
    if skipped_count > 0:
        print(f"[INFO] Skipped {skipped_count} files (already patched or incomplete)")
    
    if patched_count > 0:
        print("[INFO] ROS 2-style action wrappers applied successfully")
    
    return 0


if __name__ == '__main__':
    sys.exit(main())

