#!/usr/bin/env python3
"""
Patch all service and action types in the installed Python packages
to add ROS 2-style wrapper classes.

This script ensures rclpy compatibility by:
1. Adding wrapper classes to single-file services (e.g., CancelGoal.py)
2. Creating action wrapper files with Goal/Result/Feedback/SendGoal/GetResult/FeedbackMessage/CancelGoal
3. Updating __init__.py files to export the wrapper classes

Usage:
    python patch_ros2_type_wrappers.py <install_root>

Example:
    python patch_ros2_type_wrappers.py /opt/fast-dds-v3-libs/python/src
"""
import os
import re
import sys


def patch_single_file_service(filepath):
    """Add ROS 2-style wrapper to a single-file service (like CancelGoal.py)."""
    basename = os.path.basename(filepath).replace('.py', '')
    
    with open(filepath, 'r') as f:
        content = f.read()
    
    req_class = f"{basename}_Request"
    res_class = f"{basename}_Response"
    
    # Check if both Request and Response classes exist
    if f"class {req_class}" not in content or f"class {res_class}" not in content:
        return False
    
    # Check if wrapper already exists
    if f"class {basename}:" in content:
        print(f"  [SKIP] {filepath}: wrapper already exists")
        return False
    
    wrapper = f'''

# ROS 2-style service wrapper (auto-generated by patch_ros2_type_wrappers.py)
class {basename}:
    """ROS 2-style service type for {basename}."""
    Request = {req_class}
    Response = {res_class}
'''
    
    with open(filepath, 'a') as f:
        f.write(wrapper)
    
    print(f"  [PATCHED] {filepath}")
    return True


def update_init_py(init_path, class_name, module_name):
    """Add import to __init__.py if not present."""
    import_line = f"from .{module_name} import {class_name} as {class_name}"
    
    if not os.path.exists(init_path):
        with open(init_path, 'w') as f:
            f.write("# auto-generated\n")
    
    with open(init_path, 'r') as f:
        content = f.read()
    
    if import_line in content:
        return False
    
    with open(init_path, 'a') as f:
        f.write(f"{import_line}\n")
    
    print(f"  [INIT] Added {class_name} to {init_path}")
    return True


def patch_all_services(install_root):
    """Find and patch all single-file services."""
    print("\n=== Patching Services ===")
    
    for root, dirs, files in os.walk(install_root):
        if not root.endswith('/srv'):
            continue
        
        print(f"\nProcessing: {root}")
        
        for filename in files:
            if not filename.endswith('.py'):
                continue
            if filename.startswith('_') or filename == '__init__.py':
                continue
            if filename.endswith('_Request.py') or filename.endswith('_Response.py'):
                continue
            
            filepath = os.path.join(root, filename)
            basename = filename.replace('.py', '')
            
            if patch_single_file_service(filepath):
                init_path = os.path.join(root, '__init__.py')
                update_init_py(init_path, basename, basename)


def patch_action_file(filepath, action_name):
    """Add CancelGoal import to an action wrapper if missing."""
    with open(filepath, 'r') as f:
        content = f.read()
    
    # Check if CancelGoal is already imported
    if "CancelGoal" in content:
        return False
    
    # Check if this is a wrapper file (has class ActionName:)
    if f"class {action_name}:" not in content:
        return False
    
    # Find the class and add CancelGoal attribute
    pattern = rf"(class {action_name}:.*?)((?=\nclass |\n[^\s]|\Z))"
    
    def add_cancelgoal(match):
        class_def = match.group(1)
        if "CancelGoal" not in class_def:
            # Add before the end of class
            lines = class_def.rstrip().split('\n')
            indent = '    '
            lines.append(f"{indent}# CancelGoal service (standardized across all ROS 2 actions)")
            lines.append(f"{indent}try:")
            lines.append(f"{indent}    from action_msgs.srv import CancelGoal")
            lines.append(f"{indent}except ImportError:")
            lines.append(f"{indent}    CancelGoal = None")
            return '\n'.join(lines) + '\n'
        return class_def
    
    new_content = re.sub(pattern, add_cancelgoal, content, flags=re.DOTALL)
    
    if new_content != content:
        with open(filepath, 'w') as f:
            f.write(new_content)
        print(f"  [PATCHED] Added CancelGoal to {filepath}")
        return True
    
    return False


def create_action_wrapper(actiondir, action_name):
    """Create a ROS 2-style action wrapper file."""
    goal = f"{action_name}_Goal"
    result = f"{action_name}_Result"
    feedback = f"{action_name}_Feedback"
    sendgoal_req = f"{action_name}_SendGoal_Request"
    sendgoal_res = f"{action_name}_SendGoal_Response"
    getresult_req = f"{action_name}_GetResult_Request"
    getresult_res = f"{action_name}_GetResult_Response"
    feedback_msg = f"{action_name}_FeedbackMessage"
    
    wrapper_path = os.path.join(actiondir, f"{action_name}.py")
    
    # Check if wrapper already exists
    if os.path.exists(wrapper_path):
        # Check if it has CancelGoal
        with open(wrapper_path, 'r') as f:
            content = f.read()
        if "CancelGoal" not in content and f"class {action_name}:" in content:
            patch_action_file(wrapper_path, action_name)
        return False
    
    wrapper_content = f'''# Auto-generated ROS 2-style action wrapper for {action_name}
# Generated by patch_ros2_type_wrappers.py
from .{goal} import {goal} as Goal
from .{result} import {result} as Result
from .{feedback} import {feedback} as Feedback

# Import SendGoal/GetResult/FeedbackMessage if they exist
try:
    from .{sendgoal_req} import {sendgoal_req} as _SendGoal_Request
    from .{sendgoal_res} import {sendgoal_res} as _SendGoal_Response
    class SendGoal:
        Request = _SendGoal_Request
        Response = _SendGoal_Response
except ImportError:
    SendGoal = None

try:
    from .{getresult_req} import {getresult_req} as _GetResult_Request
    from .{getresult_res} import {getresult_res} as _GetResult_Response
    class GetResult:
        Request = _GetResult_Request
        Response = _GetResult_Response
except ImportError:
    GetResult = None

try:
    from .{feedback_msg} import {feedback_msg} as FeedbackMessage
except ImportError:
    FeedbackMessage = None

# CancelGoal service from action_msgs (standard for all ROS 2 actions)
try:
    from action_msgs.srv import CancelGoal
except ImportError:
    CancelGoal = None

class {action_name}:
    """ROS 2-style action type for {action_name}."""
    Goal = Goal
    Result = Result
    Feedback = Feedback
    SendGoal = SendGoal
    GetResult = GetResult
    FeedbackMessage = FeedbackMessage
    CancelGoal = CancelGoal
'''
    
    with open(wrapper_path, 'w') as f:
        f.write(wrapper_content)
    
    print(f"  [CREATED] {wrapper_path}")
    return True


def patch_all_actions(install_root):
    """Find and patch all action types."""
    print("\n=== Patching Actions ===")
    
    for root, dirs, files in os.walk(install_root):
        if not root.endswith('/action'):
            continue
        
        print(f"\nProcessing: {root}")
        
        # Find action names from *_Goal.py files
        action_names = set()
        for filename in files:
            if filename.endswith('_Goal.py'):
                action_name = filename.replace('_Goal.py', '')
                # Verify required files exist
                required = [f"{action_name}_Goal.py", f"{action_name}_Result.py", f"{action_name}_Feedback.py"]
                if all(os.path.exists(os.path.join(root, r)) for r in required):
                    action_names.add(action_name)
        
        for action_name in sorted(action_names):
            create_action_wrapper(root, action_name)
            init_path = os.path.join(root, '__init__.py')
            update_init_py(init_path, action_name, action_name)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <install_root>")
        print(f"  Patches all service and action types under <install_root>")
        print(f"  to add ROS 2-style wrapper classes for rclpy compatibility.")
        print(f"\nExample:")
        print(f"  {sys.argv[0]} /opt/fast-dds-v3-libs/python/src")
        sys.exit(1)
    
    install_root = sys.argv[1]
    if not os.path.isdir(install_root):
        print(f"Error: {install_root} is not a directory")
        sys.exit(1)
    
    print(f"Patching ROS 2 types in: {install_root}")
    
    patch_all_services(install_root)
    patch_all_actions(install_root)
    
    print("\n=== Done ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
