#!/usr/bin/env python3
"""
Patch service type files to add ROS 2-style wrapper classes.
For services like SetBool and Trigger, this adds wrapper classes to __init__.py
that combine Request and Response classes.
Also handles special cases like CancelGoal where Request/Response are in a single file.
"""
import os
import sys
import re

def find_service_pairs(srv_dir):
    """
    Find service Request/Response pairs in a srv directory.
    Returns a list of service base names (e.g., ['SetBool', 'Trigger']).
    """
    files = [f for f in os.listdir(srv_dir) if f.endswith('.py')]
    
    services = set()
    for filename in files:
        if filename.endswith('_Request.py'):
            service_name = filename.replace('_Request.py', '')
            response_file = f'{service_name}_Response.py'
            if response_file in files:
                services.add(service_name)
    
    return sorted(services)


def find_single_file_services(srv_dir):
    """
    Find services where Request and Response are defined in a single file.
    E.g., CancelGoal.py containing CancelGoal_Request and CancelGoal_Response classes.
    Returns a list of tuples: (service_name, filename, needs_patch).
    """
    files = [f for f in os.listdir(srv_dir) if f.endswith('.py') and not f.startswith('_') and f != '__init__.py']
    
    services = []
    for filename in files:
        # Skip if it's a _Request.py or _Response.py file
        if filename.endswith('_Request.py') or filename.endswith('_Response.py'):
            continue
        
        service_name = filename.replace('.py', '')
        filepath = os.path.join(srv_dir, filename)
        
        with open(filepath, 'r') as f:
            content = f.read()
        
        # Check if file contains both Request and Response classes
        has_request = f'class {service_name}_Request' in content
        has_response = f'class {service_name}_Response' in content
        # Check if wrapper class already exists
        already_patched = f'class {service_name}:' in content or f'class {service_name}(' in content
        
        if has_request and has_response and not already_patched:
            services.append((service_name, filename))
    
    return services


def patch_single_file_service(srv_dir, service_name, filename):
    """
    Add a wrapper class to a single-file service (like CancelGoal.py).
    """
    filepath = os.path.join(srv_dir, filename)
    
    wrapper_code = f'''
# ROS 2-style service wrapper (auto-generated by patch_service_types.py)
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {service_name}_Request
    Response = {service_name}_Response
'''
    
    with open(filepath, 'a') as f:
        f.write(wrapper_code)
    
    print(f"[PATCHED] {filepath}: added {service_name} wrapper class to file")
    return True

def patch_service_init(srv_dir):
    """
    Add ROS 2-style wrapper classes to __init__.py for all service pairs.
    """
    init_file = os.path.join(srv_dir, '__init__.py')
    if not os.path.exists(init_file):
        print(f"[SKIP] {init_file}: file not found")
        return 0
    
    with open(init_file, 'r') as f:
        content = f.read()
    
    services = find_service_pairs(srv_dir)
    if not services:
        print(f"[SKIP] {srv_dir}: no service pairs found")
        return 0
    
    patched_count = 0
    additions = []
    
    for service_name in services:
        request_class = f'{service_name}_Request'
        response_class = f'{service_name}_Response'
        
        # Check if wrapper class already exists
        if f'class {service_name}:' in content or f'class {service_name}(' in content:
            print(f"[SKIP] {service_name}: wrapper class already exists")
            continue
        
        # Check if Request/Response are imported
        if f'import {request_class}' not in content and f'from .{request_class}' not in content:
            print(f"[SKIP] {service_name}: {request_class} not imported")
            continue
        
        # Create wrapper class
        wrapper_code = f'''
# ROS 2-style service wrapper for {service_name}
class {service_name}:
    """ROS 2-style service type for {service_name}."""
    Request = {request_class}
    Response = {response_class}
'''
        additions.append(wrapper_code)
        print(f"[PATCHED] {service_name}: added wrapper class")
        patched_count += 1
    
    if additions:
        # Append all wrapper classes to __init__.py
        with open(init_file, 'a') as f:
            f.write('\n# ROS 2-style service wrappers (auto-generated by patch_service_types.py)\n')
            for wrapper_code in additions:
                f.write(wrapper_code)
    
    return patched_count


def patch_single_file_services(srv_dir):
    """
    Patch single-file services like CancelGoal.py.
    """
    services = find_single_file_services(srv_dir)
    patched = 0
    for service_name, filename in services:
        if patch_single_file_service(srv_dir, service_name, filename):
            patched += 1
    return patched


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <root_dir>")
        print(f"  Patches all srv/__init__.py files under <root_dir>/**/srv/")
        sys.exit(1)
    
    root_dir = sys.argv[1]
    if not os.path.isdir(root_dir):
        print(f"Error: {root_dir} is not a directory")
        sys.exit(1)
    
    total_patched = 0
    
    # Find all srv directories
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if not dirpath.endswith('/srv'):
            continue
        
        print(f"\n[INFO] Processing {dirpath}")
        patched_count = patch_service_init(dirpath)
        total_patched += patched_count
        
        # Also handle single-file services
        single_file_patched = patch_single_file_services(dirpath)
        total_patched += single_file_patched
    
    print(f"\n[DONE] Patched {total_patched} service wrapper classes")
    return 0

if __name__ == '__main__':
    sys.exit(main())
