name: Build & Test Ubuntu

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-ubuntu.yml

  test:
    needs: build
    uses: ./.github/workflows/test-ubuntu.yml
    with:
      build_run_id: ${{ needs.build.outputs.run_id }}
