name: Build & Test macOS

on:
  push:
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build-test-macos-wheels:
    uses: ./.github/workflows/build-macos.yml

  test-macos-wheels:
    needs: build-test-macos-wheels
    uses: ./.github/workflows/test-macos.yml
    with:
      build_run_id: ${{ needs.build-test-macos-wheels.outputs.run_id }}
