name: CI macOS

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos-wheels:
    uses: ./.github/workflows/build-macos.yml

  test-macos-wheels:
    needs: build-macos-wheels
    uses: ./.github/workflows/test-macos.yml
    with:
      build_run_id: ${{ needs.build-macos-wheels.outputs.run_id }}
